### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by iceiix** [acw/simple_asn1#4]
Latest published version on https://crates.io/crates/simple_asn1 0.1.0 is from Dec 26th, 2017, could you publish a new version from the git repo? 

Looking for a version with this commit https://github.com/acw/simple_asn1/pull/3 - upgrading the dependencies, because it has num 0.2.0 instead of num 0.1.0 (and the same minor version of the crate must be used in order to use `num` in the application and the dependency, allowing interoperability). For now I'm using the git version in my Cargo.toml:

```toml
simple_asn1 = { git = "https://github.com/acw/simple_asn1", rev = "823fc31f6f9ba0636207226901f46d50eb1fdd01" }
```

**Comment by acw** [comment]
Should be up as 0.2 now!
